# =====================================================
# НАЗВАНИЕ ПРОФИЛЯ
# =====================================================

name: "Дефолт"
# Просто название стиля.


# =====================================================
# РАССТОЯНИЯ МЕЖДУ БУКВАМИ И СЛОВАМИ
# =====================================================

kerning_mm: [0.6, 1.0]
# Случайное расстояние между буквами (в миллиметрах) [X, Y]
# Где:
# X - Минимальное расстояние
# Y - Максимальное расстояние

space_mm: [3.0, 4.5]
# Размер пробела между словами (в миллиметрах) [X, Y]
# Где:
# X - Минимальное расстояние
# Y - Максимальное расстояние

# =====================================================
# СЛУЧАЙНЫЕ ИСКАЖЕНИЯ (ЭФФЕКТ ЖИВОГО ПОЧЕРКА)
# =====================================================

scale_jitter: [-0.02, 0.02]
# Случайное изменение масштаба [X, Y]
# Буква может быть увеличена или уменьшена
# от +X% до +Y% относительно базового размера.

rotation_deg: [-0.8, 1.2]
# Случайный поворот буквы в градусах [X, Y]
# Диапазон несимметричный —
# можно имитировать почерк с лёгким наклоном.


# =====================================================
# ВЕРТИКАЛЬНЫЕ СМЕЩЕНИЯ
# =====================================================

baseline_jitter_mm: [-0.5, 0.3]
# Случайное вертикальное смещение относительно базовой линии [X, Y]
# Буквы могут:
# Опускаться до X и подниматься до Y

line_spacing_jitter_mm: [-0.1, 0.1]
# Случайная погрешность расстояния между строками [X, Y]
# Строки могут слегка сближаться или расходиться.
# Где:
# X - Опускается на X
# Y - Подымается на Y


# =====================================================
# ХВОСТАТЫЕ БУКВЫ (DESCENDERS)
# =====================================================

descenders:
  letters: ["g", "p", "q", "y", "д", "р", "у", "ф", "з"]

  anchor_top_mm: 2.5
  # Насколько выше базовой линии размещается верхняя точка (Якорь).

  anchor_jitter_mm: [-0.3, 0.5]
  # Дополнительная случайная глубина хвоста [X, Y]
  # X - опустить на минимальное значение
  # Y - опустить на максимальное значение

# =====================================================
# ПУНКТУАЦИЯ
# =====================================================

punctuation:
  letters: [".", ","]

  anchor_top_mm: 1.0
  # Насколько выше базовой линии размещается верхняя точка (Якорь).

  anchor_jitter_mm: [0.1, 0.3]
  # Случайное вертикальное смещение пунктуации [X, Y]
  # X - опустить на минимальное значение
  # Y - опустить на максимальное значение

# =====================================================
# ПЕРЕКРЫТИЕ БУКВ (СЛИТНЫЙ ПОЧЕРК)
# =====================================================

overlaps:
  б:
    right_mm: [4.5, 5.0]
  Ф:
    right_mm: [3.0, 3.5]
  Р:
    right_mm: [2.2, 2.5]
    # Насколько уменьшить логическую ширину буквы справа [X, Y]
    # X - приблизить на минимальное значение
    # Y - приблизить на максимальное значение